# Generated by Django 4.2.11 on 2024-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
